remote_theme: pages-themes/cayman@v0.2.0
title: Notes for CSE 190 Readings
description: This site contains notes for the weekly readings for CSE 190 FA24.
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one